# Generated by Django 4.2.5 on 2023-10-25 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=300)),
                ('Dob', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=300)),
                ('pin', models.CharField(max_length=300)),
                ('post', models.CharField(max_length=300)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('complaint', models.CharField(max_length=300)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('reply', models.CharField(default='pending', max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=300)),
                ('pin', models.CharField(max_length=300)),
                ('post', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
