# Generated by Django 4.2.5 on 2023-10-25 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_jobs_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Rating', models.CharField(max_length=100)),
                ('Review', models.CharField(max_length=300)),
                ('JOB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobs')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
