# Generated by Django 4.2.5 on 2023-10-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Dob',
            new_name='dob',
        ),
    ]
