# Generated by Django 4.2.5 on 2023-11-01 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_myskill_delete_own_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skil',
            new_name='skill',
        ),
    ]
