# Generated by Django 4.2.5 on 2023-11-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_skil_skill_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=500)),
            ],
        ),
    ]
