# Generated by Django 4.2.5 on 2023-11-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_refference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refference',
            old_name='course',
            new_name='narration',
        ),
        migrations.AddField(
            model_name='refference',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refference',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refference',
            name='phone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
