# Generated by Django 4.2.5 on 2023-11-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_course_refference_narration_refference_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refference',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
            preserve_default=False,
        ),
    ]
