# Generated by Django 4.2.5 on 2023-11-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_jobs_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='interview_date',
            field=models.DateField(),
        ),
    ]
